name: Test Coverage

on:
  push:
    branches:
      - main

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Download OPA Binary
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          ./opa -h

      - name: OPA test coverage
        run: |
          coverage=$( ./opa test ./bundle -c | jq '.coverage' )
          echo "COVERAGE=$coverage" >> "$GITHUB_ENV"

      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@5ba090896c84b3521c7a75bd8f4de12656e3f426 # v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: a7160df46e48dff45b24096de9302d38
          filename: csp-security-policies_coverage.json
          label: coverage
          message: ${{ (env.COVERAGE) }}
          namedLogo: Elastic
          color: green
          logoColor: lightblue
